import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Stores live station configurations, broadcast schedules, and admin updates
  stationData: defineTable({
    key: v.string(), // e.g., 'broadcast_schedule', 'station_config', 'equipo_cmnl'
    data: v.any(),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_key", ["key"]),

  // Stores users on Convex
  users: defineTable({
    id: v.string(),
    username: v.string(),
    role: v.string(),
    name: v.string(),
    classification: v.optional(v.string()),
    specialty: v.optional(v.string()),
    habitualPrograms: v.optional(v.array(v.string())),
    habitualProgramsByRole: v.optional(v.any()),
    habitualProgramsDays: v.optional(v.any()),
    avatar: v.optional(v.string()),
    mobile: v.optional(v.string()),
    email: v.optional(v.string()),
    password: v.optional(v.string()),
    permissions: v.optional(v.any()),
    coordinatorSections: v.optional(v.array(v.string())),
    tools: v.optional(v.array(v.string())),
    deviceLimitEnabled: v.optional(v.boolean()),
    authorizedDevices: v.optional(v.array(v.any())),
    interests: v.optional(v.any()),
  }).index("by_username", ["username"]),

  // Stores station documents generated by users (eliminating manual WhatsApp transfers)
  documents: defineTable({
    title: v.string(),
    contentUrl: v.string(), // File URL, base64 document or text content
    storageId: v.optional(v.id("_storage")),
    sender: v.string(), // User username / ID
    senderName: v.optional(v.string()),
    documentType: v.optional(v.string()), // 'script', 'guion', 'report', 'signature', 'official'
    status: v.string(), // 'pending', 'received', 'approved', 'archived'
    timestamp: v.string(),
    metadata: v.optional(v.any()),
  })
    .index("by_status", ["status"])
    .index("by_sender", ["sender"])
    .index("by_document_type", ["documentType"]),
});
